# Generated by Django 2.2 on 2019-06-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_customuser_songlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='songlist',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
